name = "Love's Path"
default_targets = ["win32", "win64", "appimage"]
build_directory = "Build"

love_files = [
	"*.lua",
	"*.c",
	"*.ttf",
	"*.png",
	"*.ogg",
	"*.wav",
	"*.glsl",
	"*.map"
]

win32.shared_libraries = [
	"Build/discordRPC/win32/discord-rpc.dll"
]

win64.shared_libraries = [
	"Build/discordRPC/win64/discord-rpc.dll"
]

appimage.shared_libraries = [
	"Build/discordRPC/linux/libdiscord-rpc.so"
]
